import { NextResponse } from "next/server";
import { createHash } from "crypto";
import { createClient } from "@/lib/supabase/server";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { data: contract, error } = await supabase
    .from("contracts")
    .select(
      "id, share_id, title, content, status, client_name, client_email, freelancer_signature, freelancer_signed_at, client_signature, client_signed_at, client_signed_ip, client_signed_user_agent, sent_at, created_at, updated_at"
    )
    .eq("id", id)
    .eq("user_id", user.id)
    .single();

  if (error || !contract) {
    return NextResponse.json({ error: "Contract not found" }, { status: 404 });
  }

  const { data: profile } = await supabase
    .from("profiles")
    .select("full_name, business_name, email")
    .eq("id", user.id)
    .single();

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "https://proposar.io";
  const publicLink = `${appUrl}/contract/${contract.share_id}`;

  const proofFingerprint = createHash("sha256")
    .update(
      JSON.stringify({
        id: contract.id,
        share_id: contract.share_id,
        title: contract.title,
        content: contract.content,
        status: contract.status,
        freelancer_signature: contract.freelancer_signature,
        freelancer_signed_at: contract.freelancer_signed_at,
        client_signature: contract.client_signature,
        client_signed_at: contract.client_signed_at,
        client_signed_ip: contract.client_signed_ip,
      })
    )
    .digest("hex");

  const proofText = [
    "PROPOSAR LEGAL PROOF BUNDLE",
    "===========================",
    "",
    `Generated At (UTC): ${new Date().toISOString()}`,
    `Proof Fingerprint (SHA-256): ${proofFingerprint}`,
    "",
    "CONTRACT METADATA",
    "-----------------",
    `Contract ID: ${contract.id}`,
    `Share ID: ${contract.share_id}`,
    `Title: ${contract.title}`,
    `Status: ${contract.status}`,
    `Public Link: ${publicLink}`,
    `Created At: ${contract.created_at ?? "N/A"}`,
    `Sent At: ${contract.sent_at ?? "N/A"}`,
    `Last Updated At: ${contract.updated_at ?? "N/A"}`,
    "",
    "FREELANCER / AGENCY",
    "--------------------",
    `Name: ${profile?.full_name ?? "N/A"}`,
    `Business: ${profile?.business_name ?? "N/A"}`,
    `Email: ${profile?.email ?? "N/A"}`,
    "",
    "CLIENT",
    "------",
    `Name: ${contract.client_name ?? "N/A"}`,
    `Email: ${contract.client_email ?? "N/A"}`,
    "",
    "SIGNATURE EVIDENCE",
    "------------------",
    `Freelancer Signature: ${contract.freelancer_signature ?? "PENDING"}`,
    `Freelancer Signed At: ${contract.freelancer_signed_at ?? "N/A"}`,
    `Client Signature: ${contract.client_signature ?? "PENDING"}`,
    `Client Signed At: ${contract.client_signed_at ?? "N/A"}`,
    `Client Signed IP: ${contract.client_signed_ip ?? "N/A"}`,
    `Client User Agent: ${contract.client_signed_user_agent ?? "N/A"}`,
    "",
    "CONTRACT BODY SNAPSHOT",
    "----------------------",
    contract.content ?? "",
    "",
    "DISCLAIMER",
    "----------",
    "This export is generated by Proposar as a record summary for evidentiary support.",
    "For legal proceedings, consult qualified counsel and jurisdiction-specific requirements.",
    "",
  ].join("\n");

  const fileName = `contract-proof-${contract.id}.txt`;

  return new NextResponse(proofText, {
    status: 200,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename=${fileName}`,
      "Cache-Control": "no-store",
    },
  });
}
